# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pogress-widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pogress_widget(object):
    def setupUi(self, pogress_widget):
        pogress_widget.setObjectName("pogress_widget")
        pogress_widget.setWindowModality(QtCore.Qt.WindowModal)
        pogress_widget.resize(572, 96)
        pogress_widget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        pogress_widget.setStyleSheet("background-color:#F6F6F6;\n"
"border-radius:8px;")
        self.verticalLayout = QtWidgets.QVBoxLayout(pogress_widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.p_frame = QtWidgets.QFrame(pogress_widget)
        self.p_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.p_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.p_frame.setObjectName("p_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.p_frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.p_name = QtWidgets.QLabel(self.p_frame)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.p_name.setFont(font)
        self.p_name.setStyleSheet("QLabel{\n"
"border: 0px;\n"
"color:#161D6F;\n"
"}")
        self.p_name.setObjectName("p_name")
        self.horizontalLayout.addWidget(self.p_name)
        self.p_value = QtWidgets.QLabel(self.p_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p_value.sizePolicy().hasHeightForWidth())
        self.p_value.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.p_value.setFont(font)
        self.p_value.setStyleSheet("QLabel{\n"
"border: 0px;\n"
"color:#161D6F;\n"
"}")
        self.p_value.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.p_value.setObjectName("p_value")
        self.horizontalLayout.addWidget(self.p_value)
        self.p_per = QtWidgets.QLabel(self.p_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p_per.sizePolicy().hasHeightForWidth())
        self.p_per.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.p_per.setFont(font)
        self.p_per.setStyleSheet("QLabel{\n"
"border: 0px;\n"
"color:#161D6F;\n"
"}")
        self.p_per.setAlignment(QtCore.Qt.AlignCenter)
        self.p_per.setObjectName("p_per")
        self.horizontalLayout.addWidget(self.p_per)
        self.verticalLayout.addWidget(self.p_frame)
        self.p_bar = QtWidgets.QProgressBar(pogress_widget)
        self.p_bar.setStyleSheet("QProgressBar\n"
"{\n"
"border: 1px solid #161D6F;\n"
"border-radius: 8px;\n"
"color: black;\n"
"}\n"
"QProgressBar::chunk \n"
"{\n"
"background-color: #98DED9;\n"
"border-radius :8px;\n"
"}    ")
        self.p_bar.setProperty("value", 24)
        self.p_bar.setTextVisible(False)
        self.p_bar.setObjectName("p_bar")
        self.verticalLayout.addWidget(self.p_bar)

        self.retranslateUi(pogress_widget)
        QtCore.QMetaObject.connectSlotsByName(pogress_widget)

    def retranslateUi(self, pogress_widget):
        _translate = QtCore.QCoreApplication.translate
        pogress_widget.setWindowTitle(_translate("pogress_widget", "Scale-"))
        self.p_name.setText(_translate("pogress_widget", "Image Name"))
        self.p_value.setText(_translate("pogress_widget", "24"))
        self.p_per.setText(_translate("pogress_widget", "%"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    pogress_widget = QtWidgets.QWidget()
    ui = Ui_pogress_widget()
    ui.setupUi(pogress_widget)
    pogress_widget.show()
    sys.exit(app.exec_())
